import esbuild from 'esbuild';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isDev = process.argv[2] === 'dev';

const config = {
  banner: {
    js: banner,
  },
  entryPoints: ['main.js'],
  bundle: true,
  external: ['obsidian'],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: isDev ? 'inline' : false,
  minify: isDev ? false : true,
  treeShaking: true,
  outfile: 'main.js',
  allowOverwrite: true
};

async function build() {
  if (isDev) {
    const ctx = await esbuild.context(config).catch(() => process.exit(1));
    await ctx.watch();
    console.log('Watching for changes...');
  } else {
    await esbuild.build(config).catch(() => process.exit(1));
    console.log('Build completed successfully');
  }
}

build();